//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunter.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Type
    {
        public Job_Type()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int ID { get; set; }
        public string Job_Type_Name { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
