//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunter.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Location
    {
        public Job_Location()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> State_ID { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> Zip_Code_ID { get; set; }
        public string Detail { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
