//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunter.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobHunterEntities : DbContext
    {
        public JobHunterEntities()
            : base("name=JobHunterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<City> Cities { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Field> Fields { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Job_Location> Job_Location { get; set; }
        public DbSet<Job_Type> Job_Type { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Sub_Field> Sub_Field { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_Role> User_Role { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<User_Tag> User_Tag { get; set; }
    }
}
