//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunter.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Field
    {
        public Sub_Field()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public int Field_ID { get; set; }
        public string Sub_Field_Name { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
