//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHunter.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int ID { get; set; }
        public Nullable<int> Field_ID { get; set; }
        public Nullable<int> Sub_Field_ID { get; set; }
        public string Tag_Name { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Sub_Field Sub_Field { get; set; }
    }
}
